### ISSUE TITLE
Got KeyError when set the BPR function parameters

### ISSUE THREAD

**Issue by Jame0910** [AequilibraE/aequilibrae#101]
Hi there, 

I am trying the traffic assignment according to the documentation (8.5.4. Assigning traffic on TNTP instances) using aequilibrae version 0.6.1

When I run this code:  

```assig.set_vdf_parameters({'alpha': 0.15, 'beta':4.0})```

A KeyError raised:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-111-759b5d860529> in <module>
----> 1 assig.set_vdf_parameters({'alpha': 0.15, 'beta':4.0})

~/opt/anaconda3/envs/data/lib/python3.7/site-packages/aequilibrae/paths/traffic_assignment.py in set_vdf_parameters(self, par)
    143                 else:
    144                     array = np.zeros(self.classes[0].graph.graph.shape[0], np.float64)
--> 145                     array.fill(self.vdf_parameters[p])
    146                 pars.append(array)
    147 

KeyError: 0.15
```
I have no idea how to fix it. Is there a bug inside the `traffic_assignment.py`?

Thank you.

**Comment by pedrocamargo** [comment]
Can you send the data/script you are working? Seems easy to fix, but having the data would help.

**Comment by Jame0910** [comment]
> Can you send the data/script you are working? Seems easy to fix, but having the data would help.

Thank you for your reply, this is the zip file for script and data.
[Script_data.zip](https://github.com/AequilibraE/aequilibrae/files/4240781/Script_data.zip)

**Comment by pedrocamargo** [comment]
It is fixed, and it will be available in the next release.  If you want to test it, you can go to traffic_assignment.py on line 144 and use the following code instead

`                    array.fill(self.vdf_parameters[p1])`

Note that the variable is p1, instead of p

**Comment by pedrocamargo** [comment]
It will be present in the next release

**Comment by Jame0910** [comment]
Ok I will try it. Thanks.

**Comment by pedrocamargo** [comment]
@Jame0910 , a version with a fix for the issue you reported is available on PyPi.  A full use case is also available on https://github.com/AequilibraE/aequilibrae/blob/master/docs/source/SiouxFalls.ipynb

The example data can be downloaded from https://aequilibrae.com/python/V.0.6.2/usageexamples.html
