### ISSUE TITLE
Cython code is suboptimal

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/aequilibrae#114]
We are not using accumulators inside prange, which causes OpenMP to slow down things considerably, especially for small core counts.

Reference is here: https://stackoverflow.com/questions/40451203/cython-parallel-loop-problems

**Comment by djfrancesco** [comment]
Hi Pedro, maybe this issue is not relevant anymore? It it is, where in the code do you think that `prange` is not really optimal ? Is it related to the all-or-nothing loop ?

**Comment by pedrocamargo** [comment]
Agreed
