### ISSUE TITLE
Parameter write_back error

### ISSUE THREAD

**Issue by alexdawn** [AequilibraE/aequilibrae#116]
I'm trying to get the example project to run in docker and conda to make use of jupyter notebooks, running the cell:

```python
import aequilibrae
from os.path import join
from aequilibrae import Parameters

p = Parameters()
p.parameters['system']['logging_directory'] =  fldr
p.write_back()
```

I'm getting the following error:

```
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-14-aff623fa8871> in <module>
      5 p = Parameters()
      6 p.parameters['system']['logging_directory'] =  fldr
----> 7 p.write_back()

/opt/conda/lib/python3.7/site-packages/aequilibrae/parameters.py in write_back(self)
     39     def write_back(self):
     40         """Writes the parameters back to file"""
---> 41         stream = open(self.file, "w")
     42         yaml.dump(self.parameters, stream, default_flow_style=False)
     43         stream.close()

PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.7/site-packages/aequilibrae/parameters.yml'
```

As far as I can tell the library is trying to rewrite itself which sounds a little dubious to me given Idempotency is always desirable. Is there a way of storing/reading the parameters elsewhere?

## Steps to reproduce

make the dockerfile:
```docker
FROM jupyter/scipy-notebook

USER root

RUN pip install aequilibrae
RUN pip install openmatrix
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y sqlite3 libsqlite3-dev libsqlite3-mod-spatialite
```

and run it with the bash command:

```bash
docker build --rm -t jupyter/aequilibrae .
docker run -p 8888:8888 -v "$PWD":/home/jovyan/work jupyter/aequilibrae start.sh jupyter notebook --NotebookApp.token=''
```

with the docker container now running jupyter navigate to http://localhost:8888 and try running the top snippet of python

**Comment by pedrocamargo** [comment]
This is indeed an issue, @alexdawn . I don't see this as an idempotency issue. 
Right now AequilibraE is designed to write the parameters back to its origin. 
The problem with saving it in a temporary folder is that you may end up getting those parameters during a future session without noticing it.
Any suggestions on how to deal with that in a more robust way?

**Comment by alexdawn** [comment]
I'm not sure, I'd see how other projects manages it. If it's user settings then maybe the user folder like git uses? But  lot of config seems to be project specific and should probably get saved into the filedatabase?

**Comment by pedrocamargo** [comment]
The solution here will be done with AequilibraE having a default set of parameters to load from, but as soon as you open a project, a new environment variable will be created to hold the path to the project. The location of the parameters file will follow a pre-defined structure for an AequilibraE project (the project is now a full directory, instead of a file

**Comment by pedrocamargo** [comment]
The solution has been implemented and should go under review soon, @alexdawn
