### ISSUE TITLE
Get assigment stats as panda records

### ISSUE THREAD

**Issue by alexdawn** [AequilibraE/aequilibrae#121]
Store the assignment stats that are currently being logged within the `TrafficAssignment` class for later reference as a method or attribute so it is possible to report and graph the assignment.

**Comment by pedrocamargo** [comment]
@alexdawn , Everything is already logged in aequilibrae.log, and the rgap and number of iterations are kept in the assignment object. Do you mean keeping the info for each iteration to allow you to make a convergence chart?

**Comment by alexdawn** [comment]
Yes exactly so I can chart the results and show the assignment meets the stability criteria in WebTAG as well as the final gap values. I could try and read the logs but from my understanding programs shouldn't try and read their logs.

**Comment by pedrocamargo** [comment]
That is easy to do.  However, there are two things.
They would not be a Pandas DataFrame, but rather a NumPy record array.
And what you need is probably just the final RGap, which is already available within the TrafficAssignment class. Isn't it?

**Comment by alexdawn** [comment]
Yes a numpy record is just as good.

In WebTAG Stability is the maximum change in RGap for the last four iterations but talking with some modellers they care about the entire converage chart not just the last one or the last four.

**Comment by pedrocamargo** [comment]
Addressed. Results are in a dictionary, which can be converted into a Pandas DataFrame as 
`pd.DataFrame(assig.assignment.convergence_report)`
