### ISSUE TITLE
Pipenv lock hangs in setup_dev

### ISSUE THREAD

**Issue by alexdawn** [AequilibraE/aequilibrae#123]
In the same manner as described here https://github.com/pypa/pipenv/issues/2681

equally the solution in the comments worked, with the skip-lock flag.

`python3 -m pipenv install --dev --skip-lock`

**Comment by pedrocamargo** [comment]
Can I guess this is a problem with the documentation then?  Can you take a crack at issuing a pull request to fix it?

**Comment by alexdawn** [comment]
The aequilibrae documentation is correct, I want to understand what the lock file is trying to do and why it cannot create one first before I make any changes to setup. The docs say it does this:

>--skip-lock — Ignore the Pipfile.lock and install from the Pipfile. In addition, do not write out a Pipfile.lock reflecting changes to the Pipfile.

Is that okay?

**Comment by pedrocamargo** [comment]
I think it is

**Comment by pedrocamargo** [comment]
I believe this has been fixed now.
