### ISSUE TITLE
Both 'cfw', 'bfw' and get stuck with zero step size

### ISSUE THREAD

**Issue by alexdawn** [AequilibraE/aequilibrae#124]
With version 0.6.3

Both Both 'cfw', 'bfw' and get stuck with zero step size while MSA and Frank-Wolfe options work. The log for BFW is shown below:

```
2020-04-01 11:49:53,085;aequilibrae;INFO ; bfw Assignment STATS
2020-04-01 11:49:53,089;aequilibrae;INFO ; Iteration, RelativeGap, stepsize
2020-04-01 11:49:53,089;aequilibrae;INFO ; Iteration, RelativeGap, stepsize
2020-04-01 11:49:53,207;aequilibrae;INFO ; 1,inf,1.0
2020-04-01 11:49:53,207;aequilibrae;INFO ; 1,inf,1.0
2020-04-01 11:49:53,325;aequilibrae;INFO ; 2,0.01813536336911382,0.2561015932062774
2020-04-01 11:49:53,325;aequilibrae;INFO ; 2,0.01813536336911382,0.2561015932062774
2020-04-01 11:49:53,441;aequilibrae;INFO ; 3,0.005430047866020795,0.0
2020-04-01 11:49:53,441;aequilibrae;INFO ; 3,0.005430047866020795,0.0
2020-04-01 11:49:53,561;aequilibrae;INFO ; 4,0.005430047866020795,0.0
2020-04-01 11:49:53,561;aequilibrae;INFO ; 4,0.005430047866020795,0.0
2020-04-01 11:49:53,676;aequilibrae;INFO ; 5,0.005430047866020795,0.0
2020-04-01 11:49:53,676;aequilibrae;INFO ; 5,0.005430047866020795,0.0
2020-04-01 11:49:53,794;aequilibrae;INFO ; 6,0.005430047866020795,0.0
2020-04-01 11:49:53,794;aequilibrae;INFO ; 6,0.005430047866020795,0.0
....
```

and so on until it hits the max iteration count.
The graph and demand was constructed using the Anaheim model and the assignment code copying the Sioux Falls example. I've checked the `graph.network` field names are correct.

```python

graph.set_graph('time') # let's say we want to minimize time
graph.set_skimming(['time', 'distance']) # And will skim time and distance
graph.set_blocked_centroid_flows(True)

demand = aem
# demand.load(os.path.join(data_folder, 'Anaheim_trips.omx'))
demand.computational_view(['matrix']) # We will only assign one user class stored as 'matrix' inside the OMX file

assig = TrafficAssignment()

# Creates the assignment class
assigclass = TrafficClass(graph, demand)


# The first thing to do is to add at list of traffic classes to be assigned
assig.set_classes([assigclass])

assig.set_vdf("BPR")  # This is not case-sensitive # Then we set the volume delay function

assig.set_vdf_parameters({"alpha": "b", "beta": "power"}) # And its parameters

assig.set_capacity_field("capacity") # The capacity and free flow travel times as they exist in the graph
assig.set_time_field("time")

# And the algorithm we want to use to assign
# ['all-or-nothing', 'msa', 'frank-wolfe', 'cfw', 'bfw']
assig.set_algorithm('bfw')  #Biconjugate Frank-Wolfe

# since I haven't checked the parameters file, let's make sure convergence criteria is good
assig.max_iter = 50
assig.rgap_target = 0.00005

assig.execute() # we then execute the assignment
```

**Comment by pedrocamargo** [comment]
I was able to reproduce the problem, so I will now debug and update the reason

**Comment by pedrocamargo** [comment]
`import os
import sys
import pandas as pd
import numpy as np
import openmatrix as omx
from aequilibrae.matrix import AequilibraeMatrix
from aequilibrae.paths import Graph

data_folder = 'D:/src/TransportationNetworks/Anaheim'

from aequilibrae import logger
import logging
# We redirect the logging output to the terminal
stdout_handler = logging.StreamHandler(sys.stdout)
logger.addHandler(stdout_handler)
`

**Comment by pedrocamargo** [comment]
Code to reproduce error

https://gist.github.com/pedrocamargo/459501b6390e4b41af735bc8566b547a

**Comment by pedrocamargo** [comment]
The problem occurs when none of the algorithms based on line searches can find a good value, but only FW had the ability to default to MSA, while the others would only go as far down as FW.

**Comment by janzill** [comment]
Good catch @alexdawn If either CFW or BFW cannot find an appropriate step size we should re-start from FW, which I thought was implemented but we obviously made a mistake somewhere. Thoughts @pedrocamargo ?

**Comment by janzill** [comment]
Oh man, I'm late to the party, just saw your PR @pedrocamargo sorry :D

**Comment by pedrocamargo** [comment]
It was actually pretty easy to fix!
