### ISSUE TITLE
Tracing back the origins or destinations from a given link or node

### ISSUE THREAD

**Issue by YuryZammit** [AequilibraE/aequilibrae#152]
I have a question in relation to the functionality of Aequilibrae.  Once a traffic assignment has been set, is it possible to trace back the origins or destinations from a given link or node?

For example, as a result of the assignment, there are 100 vehicles that flow on Link A.  Can I determine what are the origins of those 100 vehicles on Link A ? Can it be mapped?

This might show potential improvements to the transport network or services.  If say 30% of vehicles on Link A arrive from a cluster of origins, one might suggest investigating potential public transport route that will take a share of those trips.

**Comment by pedrocamargo** [comment]
Some background discussion on this

https://groups.google.com/forum/#!topic/aequilibrae/bs5-3itqqUs

**Comment by pedrocamargo** [comment]
Hey @YuryZammit , we are working on this feature (https://github.com/AequilibraE/aequilibrae/pull/243), but there is still some work to be done.  Do you know of any project or other funding source that would allow us to finish this piece?

**Comment by YuryZammit** [comment]
Hi Pedro,

I'll make some enquiries and get back to you

Yury

**Comment by pedrocamargo** [comment]
@YuryZammit , we have developed Select-link analysis https://github.com/AequilibraE/aequilibrae/pull/377 and it will be released soon
