### ISSUE TITLE
assignment result doesn't contain od_flows

### ISSUE THREAD

**Issue by 741311791** [AequilibraE/aequilibrae#153]
I use the AequilibraE package in metro planning, the assignment result doesn't contain station-pair flows, I have to use networkx to get what i want, so, can you fix it?

**Comment by pedrocamargo** [comment]
Hi. I have absolutely no idea what are you calling station-pairs. 
More than that, without more information, there is absolutely nothing that can be done.
Please remember that this is free software developed by volunteers, so the least you can do is to put some effort in detailing the issue you are reporting.

**Comment by 741311791** [comment]
I'm sorry about that. What I mean is I want to get paths and path_nodes between two nodes just like path_compute API, but I don't want to compute one by one, is there any fast method to get all paths and  path_nodes between the zones.

**Comment by pedrocamargo** [comment]
What you want is the entire path for a series of ODs?   That has absolutely NOTHING to do with assignment, and also there is nothing to fix. You are asking for a new feature, so there is nothing to be fixed..

AequilibraE does not have a way to compute path trees in bulk (it is easy to hack it done, but no current easy way).  The fastest way is to look it through your ODs by origin and do all the destinations one by one using the **update_trace** method of the  PathComputation class, as that does not re-compute the underlying shortest-path tree.

https://aequilibrae.com/python/dev/_generated/aequilibrae.PathResults.html#aequilibrae.PathResults

The next time, before reporting an issue, send your questions to the users mailing list.
