### ISSUE TITLE
QGIS freezes when starting a new project from OSM

### ISSUE THREAD

**Issue by andreaCola** [AequilibraE/aequilibrae#164]
I was trying to initialise a project by downloading OSM from canvas.
I left it downloading for more than 2 hours, but couldn't see any progress and eventually QGIS crashed.
Also tried on another machine with same result.

I'm using QGIS 3.12 on a windows machine.
Didn't do any spatialite installation when I tried.

**Comment by pedrocamargo** [comment]
@andreaCola , this is an issue for the other repo (the QGIS one)

**Comment by andreaCola** [comment]
opened in the QGIS repo
