### ISSUE TITLE
Transit mode 

### ISSUE THREAD

**Issue by orlandoandradeb** [AequilibraE/aequilibrae#169]
Hello every one 

I would like just to get a confirmation about a  feature. Reading the documentation I see that now is not possible to integrate to the demand model the transit system correct? 
So the actual modules of modeling are just focus in car ? 

Thank you

**Comment by pedrocamargo** [comment]
This is an issue tracker, not a Q&A board.  Send your questions to aequilibrae@googlegroups.com
