### ISSUE TITLE
Traffic assignment accuses error that shouldn't exist

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/aequilibrae#182]
**Purpose of use**
Unknown

**Describe the bug**
Traffic assignment points to incompatibility between centroids in the network and in the matrix even when they are exactly the same.

**To Reproduce**
Use attached files in AequilibraE for QGIS

**Expected behavior**
Should work perfectly

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.8
 - Version 0.6.4

** Dataset for reproduction
[Sarandi.zip](https://github.com/AequilibraE/aequilibrae/files/5368188/Sarandi.zip)

**Comment by jamiecook** [comment]
To hotfix this in existing versions of Aequilibrae prior to release of 0.7, go to the Python file at  
`C:\Users\YOUR_USER_NAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE-GUI\aequilibrae\aequilibrae\project\network\network.py`

And replace line 281, change it from this

```python
curr.execute('select node_id from nodes where is_centroid=1;')
```

To this
```python
curr.execute('select node_id from nodes where is_centroid=1 order by node_id;')
```
