### ISSUE TITLE
DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by SahandAsgarpour** [AequilibraE/aequilibrae#184]
Hi,

I would be really grateful if someone could help me with the following issue.

I am trying to install the AequilibraE plug-in. When I install it, I get the following error:

**Error**
**_AequilibraE cannot find the method _classFactory()_**

**_ImportError:DLL load failed: The specified module could not be found._**

_Python versie:_ 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
_QGIS versie:_ 3.10.10-A Coruña A Coruña, 8b051b9a43 

**My actions so far**

1. Uninstalled the QGIS completely (with deleting the folders) and Reinstall it again and tried to install the plug-in again

2. Tried QGIS 3.14 and 3.10

**Comment by pedrocamargo** [comment]
This question was asked multiple times. Please look at the old emails. Cheers, Pedro  ---- On Fri, 23 Oct 2020 00:26:22 +1000  notifications@github.com  wrote ----

Hi,

I would be really grateful if someone could help me with the following issue.

I am trying to install the AequilibraE plug-in. When I install it, I get the following error:

Error

_AequilibraE cannot find the method classFactory()

ImportError:DLL load failed: The specified module could not be found.

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS versie: 3.10.10-A Coruña A Coruña, 8b051b9a43

My actions so far





Uninstalled the QGIS completely (with deleting the folders) and Reinstall it again and tried to install the plug-in again





Tried QGIS 3.14 and 3.10

**Comment by pedrocamargo** [comment]
@SahandAsgarpour , this is NOT a bug.  Join the mailing group (https://groups.google.com/g/aequilibrae) or simply look into the mail history.

**Comment by SahandAsgarpour** [comment]
Thank you very much Pedro!
