### ISSUE TITLE
Can't add AequilibraE plugin

### ISSUE THREAD

**Issue by wangsicheng1988** [AequilibraE/aequilibrae#195]
I could not add AequilibraE plugin into QGIS (3.12). It says "An error occurred during execution of following code: pyplugin_installer.instance().installFromZipFile(r'D:\0000_Chicago_access\aequilibrae-master.zip')

**Comment by pedrocamargo** [comment]
@wangsicheng1988 ,  I am closing this issue for 3 reasons:

1. This is NOT the repository for the QGIS plugin
2. You have NOT followed the instructions on the issue reporting templates
3. You have not provided complete information on the issue
