### ISSUE TITLE
Add conical volume delay function

### ISSUE THREAD

**Issue by ssmith55** [AequilibraE/aequilibrae#204]
We are using AequilibraE as a fast supplemental routing model, where the core travel demand model uses a conical VDF.  

We would like to use the same conical VDF in our AequilibraE routing.  
![image](https://user-images.githubusercontent.com/25960780/104071527-57ee8500-51d7-11eb-9ef3-f7011f71b148.png)

**Comment by pedrocamargo** [comment]
So we have the function as this 
![image](https://user-images.githubusercontent.com/7377666/104588847-b70b3880-56b4-11eb-9aec-9017c80bf2ca.png)

And the derivative as this:

![image](https://user-images.githubusercontent.com/7377666/104588875-c25e6400-56b4-11eb-83a1-75136c789ee1.png)

Where x is the volume. Can you check/confirm that, @ssmith55 ?

**Comment by ssmith55** [comment]
Yes, VC is volume/capacity ratio, e.g., x/c.  Thanks.

**Comment by pedrocamargo** [comment]
@ssmith55 , I have done the initial implementation in C/Cython, but it would be good if you could check it as well.  The Pull request is this one https://github.com/AequilibraE/aequilibrae/pull/210

Can you also provide a reasonable range of parameter values (something you have recently encountered in practice) so I can write the tests?

**Comment by ssmith55** [comment]
A few sample values:
alpha = 9,  beta = 1.06   used for freeways
alpha = 4.5, beta = 1.14, used for arterials
alpha = 2, beta = 1.5, used for locals

**Comment by ssmith55** [comment]
Some calculated values to check against (I implemented them on a spreadsheet)
alpha | 9 | 2
-- | -- | --
beta | 1.06 | 1.5
x/c | freeway | local
0 | 0.9977976245 | 1
0.2 | 0.9826952307 | 0.9147697833
0.4 | 0.958723412 | 0.8190428973
0.6 | 0.9150702453 | 0.7142857143
0.8 | 0.8137205209 | 0.6051739457
1 | 0.5 | 0.5
1.2 | 0.2070855065 | 0.4077609185
1.4 | 0.1205863543 | 0.3333333333
1.6 | 0.0844376818 | 0.276171589
1.8 | 0.0648608982 | 0.2329280499
2 | 0.0526254654 | 0.2

**Comment by pedrocamargo** [comment]
I think your results are inverted (as in 1/x), @ssmith55 . The values for the function are decreasing as v/c increase?  I got the following values for the freeway parameters. Or I guess those values are for speeds...

[ 1.          1.0176095   1.0430537   1.09281228  1.22892317  2.    4.82892317  8.29281228 11.8430537  15.4176095  19.00220724]

**Comment by ssmith55** [comment]
Yes, the values in my table are for speeds (which is how the MPO reported them in their methodology report).  And they are the inverse of the values that you got.  Sorry for the confusion.

**Comment by pedrocamargo** [comment]
This is how the function will appear in the documentation:  

![image](https://user-images.githubusercontent.com/7377666/104597417-07889300-56c1-11eb-8c48-009a60cac44b.png)

**Comment by pedrocamargo** [comment]
The implementation is ready, @ssmith55 .  Give it a few minutes for the CI workflow to run and you will be able to see the documentation here:  https://aequilibrae.com/python/dev/traffic_assignment.html 

Is there anything else you would like to see in the documentation?  I added the reference to Spiess' original paper, but are there any practical results/references we can reference in there to guide people on how to use this function?

**Comment by ssmith55** [comment]
My source was section 7.3 of HRTPO's methodology report: 
 https://www.hrtpo.org/uploads/docs/2020_HamptonRoads_Modelv2_MethodologyReport.pdf

**Comment by pedrocamargo** [comment]
Thanks, I added it to the documentation

**Comment by pedrocamargo** [comment]
Merged into master. Will be in the next release, @ssmith55
