### ISSUE TITLE
Read General Modeling Network Specification (GMNS) networks

### ISSUE THREAD

**Issue by ssmith55** [AequilibraE/aequilibrae#205]
[GMNS](https://github.com/zephyr-data-specs/GMNS) is an open specification for sharing networks.  Request that AequilibraE be able to use networks in GMNS format (nodes and links).   A few notes on GMNS:
-  Vehicle links are directed.  Pedestrian links are undirected 
- GMNS links include attributes such as length, facility_type (e.g., functional class), free_speed.  They do not include parameters for the volume delay function
- Any GMNS element may have optional user-defined fields.

**Comment by ssmith55** [comment]
The GMNS team has developed a very basic set of tools for AequilibraE 0.6.5.  Our tools
-   Convert a trip list to a trip table in OMX format (can AequilibraE deal with trip lists directly, e.g., o_zone, d_zone, volume as a csv file with many rows?)
-   Put nodes and links into an AequilibraE SQLite database, using a lookup table of link performance (VDF)
See https://github.com/zephyr-data-specs/GMNS/tree/Lima/Small_Network_Examples/Lima/AequilibraE

**Comment by pedrocamargo** [comment]
@ssmith55 , This capability is being implemented. Can you or someone working with you take a look at the PR to see if it aligns with what you know about GMNS?  @daniloebbinghaus and I are not completely across the standard, so we might have missed something

**Comment by ssmith55** [comment]
Thank you for this effort.  Our latest work on GMNS is in https://github.com/zephyr-data-specs/GMNS/tree/development   There is not much change to the spec itself, apart from a bit of clean up on data-types (now using NUMERIC instead of DOUBLE or INTEGER in cases where it doesn't matter).  A few notes:
1. In our own conversion from GMNS to AequilibraE, we have been looking for node_type = "centroid", and setting is_centroid = 1 on those nodes (however, this convention is not part of the GMNS spec)
2.  Units for link capacity in GMNS are veh / hr / lane, while in AequiibraE they are veh / hr, right?  Will need to multiply by the number of lanes in making the conversion.  
3.  GMNS link length is NUMERIC, in miles or km.   (what we call long_length units)
@ianberg-volpe, other thoughts?

**Comment by ianberg-volpe** [comment]
Hi @ssmith55, I will take a look at the PR next week.

**Comment by pedrocamargo** [comment]
That has now been integrated in the main software
