### ISSUE TITLE
Create Sioux Falls example and cannot open it

### ISSUE THREAD

**Issue by Carolimi** [AequilibraE/aequilibrae#213]
I've created/downloaded the Sioux Falls exemple by running the code sugested in https://aequilibrae.com/python/latest/_auto_examples/plot_forecasting.html#sphx-glr-auto-examples-plot-forecasting-py :
```
from uuid import uuid4
from tempfile import gettempdir
from os.path import join
from aequilibrae.utils.create_example import create_example
from aequilibrae import logger
import logging
import sys
fldr = join(gettempdir(), uuid4().hex)
project = create_example(fldr)
```
Then, in another code, i've tried to open the data using:

```
project = Project()
project.open(fldr)
```
 And i have recieved the following error:  
**File "C:\Users\carolimi\AppData\Roaming\Python\Python38\site-packages\aequilibrae\project\network\osm_utils\osm_params.py", line 4, in <module>
    par = Parameters().parameters['osm']

KeyError: 'osm'**

**Desktop**

OS: Windows 10
QGIS Version [3.10 64 bits]
AequilibraE Version [0.6.2]

**Comment by pedrocamargo** [comment]
@Carolimi , the solution has been implemented and will be available in the next release.

https://github.com/AequilibraE/aequilibrae/pull/214
