### ISSUE TITLE
Volume-independent portion of the objective function is being multiplied by the PCEs

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/aequilibrae#239]
**Purpose of use**
Multi-class traffic assignment with PCEs different than one

**Describe the bug**
Poor convergence of traffic assignment

**To Reproduce**
Perform traffic assignment with multiple classes and PCEs different than 1.0

**Expected behavior**
Better convergence

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - Python version: 3.7.9
 - Version: 0.7.2 Dev

**Comment by janzill** [comment]
@pedrocamargo to recap our conversation: 

1. To be able to write the user equilibrium problem as a convex optimization problem, we need to have pces that are constant per class and factor these out of the cost function, i.e. we need to express demand in terms of car units.
2. When using generalised cost, we need to make sure that we do not have a class-specfic pre-factor on the volume-dependent part of the generalised cost. In other words, we need to use units of time for the generalised cost.
3. We need to make sure that units are consistent. Let's say we have two classes and besides the vdf part, we have a link-based toll. Now, you would usually specify this in $/vehicle, but the demand is in units of pce, so we need to be very specific in what the user is supposed to give as input compared to what we do internally.
4. For comparison, I checked EMME's documentation for multi-class SOLA, and they are not clear on the fixed cost bit as far as I can tell, but they require the user to specify the generalised cost function in units of time and to provide demand in pces.
