### ISSUE TITLE
Error during 'set_skimming' process

### ISSUE THREAD

**Issue by andresabarca2** [AequilibraE/aequilibrae#247]
I have been testing AequilibraE in Google Colab, it seems to me like a good way to go around the process of installing the components in Windows and also its a very portable solution. I managed to get everything working for the examples in your website, the Sioux Falls projects runs great.

I created my network with the QGIS package (it is not a huge network, it has a little over 3000 links)  and I got it to run correctly there, all the way to the assignment of my demand. I'm very happy about that.

I also went through the process of updating my GIS network to the 0.7 version as you told me but I think there's probably something wrong with it.

It loads in Python (I can see the link and node data), it creates the graphs, but when I try to define the skimming (graph.set_skimming) it gives an error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-483409e42323> in <module>()

---> 10 graph.set_skimming(['free_flow_time', 'distance'])

/usr/local/lib/python3.7/dist-packages/aequilibrae/paths/graph.py in set_skimming(self, skim_fields)
    473         df = self.__graph_groupby.sum()[skim_fields].reset_index()
    474         for i, skm in enumerate(skim_fields):
--> 475             self.compact_skims[df.index.values, i] = df[skm].values[:].astype(self.__float_type)
    476
    477         self.skims = np.zeros((self.num_links, len(skim_fields) + 1), self.__float_type)

IndexError: index 2634 is out of bounds for axis 0 with size 2634

 - OS: Google Colab (Linux)
 - Python = 3.7
 - Version ?
 - 
[network_v07.zip](https://github.com/AequilibraE/aequilibrae/files/6265155/network_v07.zip)

**Comment by janzill** [comment]
@andresabarca2 thanks for the bug report and for providing your data. I had a quick look and I think I know what's going on, see #248

**Comment by pedrocamargo** [comment]
@andresabarca2 , there will be a release in the coming weeks including this fix.  Thanks to @janzill !!!
