### ISSUE TITLE
getting a value error issue - ValueError: Matrix and graph do not have compatible sets of centroids. 

### ISSUE THREAD

**Issue by Kavehj** [AequilibraE/aequilibrae#250]
I created a simple network and in python a openmatrix file which contains my demand (0-D) matrix. when load the demand matrix to assignment and then press 'Add traffic class to assignment', I am receiving the above error message. Checking my network the zones in my TAZ (omx index) and centroids have the same ids. Not quite sure then where the issue is from.

**Comment by pedrocamargo** [comment]
@Kavehj , one needs to be able to replicate the issue in order to solve it.  Please open a new bug report using the template provided.

**Comment by jamiecook** [comment]
This is actually a duplicate of #182 - hot fixing instructions repeated here

To hotfix this in existing versions of Aequilibrae prior to release of 0.7, go to the Python file at  
`C:\Users\YOUR_USER_NAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE-GUI\aequilibrae\aequilibrae\project\network\network.py`

And replace line 281, change it from this

```python
curr.execute('select node_id from nodes where is_centroid=1;')
```

To this
```python
curr.execute('select node_id from nodes where is_centroid=1 order by node_id;')
```
