### ISSUE TITLE
Assignment bug

### ISSUE THREAD

**Issue by Kavehj** [AequilibraE/aequilibrae#251]
**Purpose of use**
Are you reporting something you found during a research project, consulting/professional project or personal project?

This is a research project

Is that a funded project?

No

**Describe the bug**
I have created a demand matrix and also a project with nodes and links and I wish to do a simple all or nothing assignment with length only. 

When I click on "add traffic class to assignment", I get the following message (see --1 below). Checking the centroid numbers and OMX demand matrix zone labels, the numbering system are identical so I cannot understand the reason for the following message, 

---1
"ValueError: Matrix and graph do not have compatible sets of centroids. 
Traceback (most recent call last):
  File "C:/Users/kjaha/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AequilibraE\paths_procedures\traffic_assignment_dialog.py", line 253, in __create_traffic_class
    assigclass = TrafficClass(graph, self.matrix)
  File "C:\Users\kjaha\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae\aequilibrae\paths\traffic_class.py", line 11, in __init__
    raise ValueError("Matrix and graph do not have compatible sets of centroids.")
ValueError: Matrix and graph do not have compatible sets of centroids.

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.18.0-Zürich Zürich, bdef9fb328 

Python Path:
C:\Users\kjaha\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\aequilibrae
C:/OSGEO4~1/apps/qgis/./python
C:/Users/kjaha/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/kjaha/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/kjaha/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\kjaha\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE\paths_procedures/aequilibrae/"
---1

**To Reproduce**
1. Open the project (tried to attach but the file is not github supported)
2. Click on path and assignment and then traffic assignment and try loading the attached demand matrix and then click on 
   "add traffic class to assignment"
3. See error

Happy to send the data and files separately if needed. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python version

**Additional context**
Add any relevant data to this issue you are reporting.

**Comment by jamiecook** [comment]
@Kavehj I would suggest 

1. Clearly demonstrating the results of your checking - screenshots of zone numbers in omx and centroid layer
2. List the version of aequilibrae you are using
3. Try uploading your project as a zip file

**Comment by pedrocamargo** [comment]
@Kavehj , This is NOT the repository for this issue.  You are having problems with the QGIS plugin, and NOT the Python library. 
The issue tracker is this: https://github.com/AequilibraE/AequilibraE-GUI/issues
There is also a solution for this problem in the users' mailing list

**Comment by pedrocamargo** [comment]
@Kavehj , If you do file a bug report on the appropriate repository, please remember to fill in the **entire** template and provide testing data.

**Comment by jamiecook** [comment]
This is actually a duplicate of #182 - hot fixing instructions repeated here

To hotfix this in existing versions of Aequilibrae prior to release of 0.7, go to the Python file at  
`C:\Users\YOUR_USER_NAME\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\AequilibraE-GUI\aequilibrae\aequilibrae\project\network\network.py`

And replace line 281, change it from this

```python
curr.execute('select node_id from nodes where is_centroid=1;')
```

To this
```python
curr.execute('select node_id from nodes where is_centroid=1 order by node_id;')
```
