### ISSUE TITLE
Error when trying to add centroid

### ISSUE THREAD

**Issue by daniloebbinghaus** [AequilibraE/aequilibrae#285]
Basically, it seems that when we have a node previously located at the geometric center of a zone, the method "add_centroid(None)" doesn't create a centroid and returns the following error (image below):

![add_centroid_bug](https://user-images.githubusercontent.com/91709021/144677388-c76f64b9-9159-4409-8ed0-34aa58ccab75.png)

**Comment by pedrocamargo** [comment]
@daniloebbinghaus , do you have that query/code that allowed you to get around this?

**Comment by daniloebbinghaus** [comment]
Yes, @pedrocamargo. The code is here:

```ruby
sql = """SELECT count(*) FROM nodes
            WHERE  nodes.geometry = GeomFromWKB(?, 4326) AND
         nodes.ROWID IN (
          SELECT ROWID FROM SpatialIndex WHERE f_table_name = 'nodes' AND
          search_frame = GeomFromWKB(?, 4326))
      """

zones_list = [x[0] for x in proj.conn.execute("select zone_id from zones where zone_id not in (select node_id from nodes)")]

for z_id in zones_list:
    zone = zoning.get(z_id)
    centroid = zone.geometry.centroid

    while True:
        test_list = proj.conn.execute(sql, [centroid.wkb, centroid.wkb]).fetchall()
        if test_list[0][0] == 0:
            break

        centroid = Point(zone.geometry.centroid.x + random.random()*0.0003, zone.geometry.centroid.y + random.random()*0.0003)
        
    zone.add_centroid(centroid)
```

So, adding randomly shifted centroids to all zones with nodes located at their very geometric centers ended up working as a workaround. I had to use that sql query to check if there was already a node located at the same position as the centroid.
