### ISSUE TITLE
[Q] warnings.warn vs logger.warning

### ISSUE THREAD

**Issue by elfjes** [AequilibraE/aequilibrae#324]
I've noticed that Aequilibrae sometimes uses `starts_logging.logger.warning` to throw warnings, eg https://github.com/AequilibraE/aequilibrae/blob/c3dfaf0b9f375027018c7a0e099f93734684a259/aequilibrae/paths/graph.py#L368, and sometimes `warnings.warn`, eg https://github.com/AequilibraE/aequilibrae/blob/c3dfaf0b9f375027018c7a0e099f93734684a259/aequilibrae/paths/graph.py#L387

Is there a specific reason for this? I'm asking because I'm looking for a way to disable the warnings raised using `warnings.warn`; we'd like to hide them in our applications. If they could all be given to `logger.warning`, that'd be the simplest approach.

**Comment by pedrocamargo** [comment]
Initially, they were all warnings, but we switched to logger warnings at some point without refactoring properly).  

I think the right way to go here would be to switch to logger warnings and then you can disable it by just setup the logging level for AequilibraE to ERROR.  Does that make sense?

**Comment by elfjes** [comment]
Yep, sounds straightforward :) I'll be working on a PR sometime soon

**Comment by pedrocamargo** [comment]
That sounds reasonable.  I would remove the global logging folder, though.  In my experience people don;t actually use it, so we can just default to `gettempdir()` and call it a day. Does that sound reasonable?
