### ISSUE TITLE
[Suggestion] IPF - use factor estimation instead

### ISSUE THREAD

**Issue by raplam** [AequilibraE/aequilibrae#328]
Hello,
I noticed that the Iterative Proportional Fitting implemented in ipf.py is an implementation of the naive/classical IPF algorithm. The Wikipedia page on [Iterative Proportional Fitting ](https://en.wikipedia.org/wiki/Iterative_proportional_fitting) explains why the version based on factor estimation is "at least one order in magnitude faster". For my modeling purposes at least, I found the time saving to be quite significant. I hope it helps... and take this opportunity to thank you for making your model open-source!
Best regards.

**Comment by pedrocamargo** [comment]
Hi @raplam, I have never seen the need for it, as all the instances I worked on were blazing fast, but we would welcome a pull request with the new algorithm

**Comment by raplam** [comment]
Hi @pedrocamargo. Thanks for your quick answer! The computational time on my side  was not so short (between 5 and 50 s per fitting, depending on the instance, with a gap criterion of 0.01). It's not the end of the world but it makes the calibration a bit lengthy. It might however be due the problem size I am considering (about 8'000 zones). I must also say that I ran my own code, which follows the same matrix-based structure as yours but could contain other issues. As I haven't switched yet to actually use AequilibraE, I do not intend to submit a pull request. 
Regards

**Comment by pedrocamargo** [comment]
Tests I ran were for matrices with up to 5000 zones and it was pretty fast, so it might be something to do with the data structure.
