### ISSUE TITLE
Packaging yields file that fails to import on Linux systems.

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/aequilibrae#363]
All wheels being generated work succeffuly, but the *.tar.gz file that is generated fails to install in Linux systems.

This seems to be an issue.

**Comment by djfrancesco** [comment]
What is the error message you are getting ? I tried and got the following one :
```
      running build_ext
      cythoning /tmp/pip-req-build-p79jz_cm/aequilibrae/paths/AoN.pyx to /tmp/pip-req-build-p79jz_cm/aequilibrae/paths/AoN.cpp
      error: /tmp/pip-req-build-p79jz_cm/aequilibrae/paths/AoN.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aequilibrae
Failed to build aequilibrae
ERROR: Could not build wheels for aequilibrae, which is required to install pyproject.toml-based projects
```
Is i the same one ?

**Comment by pedrocamargo** [comment]
YUP!

**Comment by djfrancesco** [comment]
From what I understand, the original pyx file is transformed by Cython and cannot be found in the source distribution. It is possible to include these files with MANIFEST.in (see 7d52684b693ccd1c1b2a5b421e902c43bf16e731). This  is what worked for me. Then I can run successfully:
```
python setup.py sdist --formats=gztar
pip install dist/aequilibrae-0.7.6.tar.gz
```
Does that help @pedrocamargo?

**Comment by pedrocamargo** [comment]
This has been resolved
