### ISSUE TITLE
Installing on Mac M1 - crash on pyqt5

### ISSUE THREAD

**Issue by RafalKucharskiPK** [AequilibraE/aequilibrae#379]
I cannot install `AequilibraE` on my Mac with `pip`

It seems ot crash on pyqt5:

> """ rafalkucharski@MacBook-Pro-Rafa ~ % pip install aequilibrae
> Collecting aequilibrae
>   Using cached aequilibrae-0.7.7.tar.gz (1.8 MB)
>   Installing build dependencies ... error
>   error: subprocess-exited-with-error
>   
>   × pip subprocess to install build dependencies did not run successfully.
>   │ exit code: 1
>   ╰─> [61 lines of output]
>       Collecting setuptools
>         Using cached setuptools-67.1.0-py3-none-any.whl (1.1 MB)
>       Collecting numpy<1.22
>         Downloading numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
>            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 6.8 MB/s eta 0:00:00
>       Collecting cython
>         Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
>       Collecting pyaml
>         Using cached pyaml-21.10.1-py2.py3-none-any.whl (24 kB)
>       Collecting pyqt5
>         Using cached PyQt5-5.15.8.tar.gz (3.2 MB)
>         Installing build dependencies: started
>         Installing build dependencies: finished with status 'done'
>         Getting requirements to build wheel: started
>         Getting requirements to build wheel: finished with status 'done'
>         Preparing metadata (pyproject.toml): started
>         Preparing metadata (pyproject.toml): finished with status 'error'
>         error: subprocess-exited-with-error
>       
>         × Preparing metadata (pyproject.toml) did not run successfully.
>         │ exit code: 1
>         ╰─> [29 lines of output]
>             Traceback (most recent call last):
>               File "/Users/rafalkucharski/miniforge3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
>                 hook = backend.prepare_metadata_for_build_wheel
>             AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
>       
>             During handling of the above exception, another exception occurred:
>       
>             Traceback (most recent call last):
>               File "/Users/rafalkucharski/miniforge3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
>                 main()
>               File "/Users/rafalkucharski/miniforge3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
>                 json_out['return_val'] = hook(**hook_input['kwargs'])
>               File "/Users/rafalkucharski/miniforge3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
>                 whl_basename = backend.build_wheel(metadata_directory, config_settings)
>               File "/private/var/folders/11/v91c3qb92lg10fbgz1ptll4m0000gn/T/pip-build-env-tgu1esa4/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
>                 project = AbstractProject.bootstrap('wheel',
>               File "/private/var/folders/11/v91c3qb92lg10fbgz1ptll4m0000gn/T/pip-build-env-tgu1esa4/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
>                 project.setup(pyproject, tool, tool_description)
>               File "/private/var/folders/11/v91c3qb92lg10fbgz1ptll4m0000gn/T/pip-build-env-tgu1esa4/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 585, in setup
>                 self.apply_user_defaults(tool)
>               File "/private/var/folders/11/v91c3qb92lg10fbgz1ptll4m0000gn/T/pip-install-wc89xob1/pyqt5_9a1165a045ff47f28c505d69fbefeca4/project.py", line 69, in apply_user_defaults
>                 super().apply_user_defaults(tool)
>               File "/private/var/folders/11/v91c3qb92lg10fbgz1ptll4m0000gn/T/pip-build-env-tgu1esa4/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
>                 super().apply_user_defaults(tool)
>               File "/private/var/folders/11/v91c3qb92lg10fbgz1ptll4m0000gn/T/pip-build-env-tgu1esa4/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
>                 self.builder.apply_user_defaults(tool)
>               File "/private/var/folders/11/v91c3qb92lg10fbgz1ptll4m0000gn/T/pip-build-env-tgu1esa4/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
>                 raise PyProjectOptionException('qmake',
>             sipbuild.pyproject.PyProjectOptionException
>             [end of output]
>       
>         note: This error originates from a subprocess, and is likely not a problem with pip.
>       error: metadata-generation-failed
>       
>       × Encountered error while generating package metadata.
>       ╰─> See above for output.
>       
>       note: This is an issue with the package mentioned above, not pip.
>       hint: See above for details.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> """

**Desktop (please complete the following information):**
 - OS: Ventura, Apple M1 on MacBookPro
 - Python version: 3.10.8
 - Version: pip

**Additional context**
Add any relevant data to this issue you are reporting.

**Comment by pedrocamargo** [comment]
@RafalKucharskiPK , This is an upstream issue, so we have no control. I also don't have a machine with an M1 chip available for testing.  What you can do for now is to install aequilibrae with the **--no-deps** flag and install all other requirements (e.g. scipy) manually.

**Comment by jamiecook** [comment]
Note that a new 0.9.1 version is now out which may install more smoothly on
your machine.
If not I might have to spin up an AWS instance to see what is happening
with the M1 chips.

- Jamie
http://jamiecook.wordpress.com

**Comment by lindsaymorgan** [comment]
> @RafalKucharskiPK , This is an upstream issue, so we have no control. I also don't have a machine with an M1 chip available for testing. What you can do for now is to install aequilibrae with the **--no-deps** flag and install all other requirements (e.g. scipy) manually.

I am now trying to install AequilibraE in an arm64 base linux machine. I installed PyQt5 in advance but still met this problem. I also tried to add --no-deps flag but the install process still tried to install pyqt5 by itself. Is there any other solution? Or could it compile and it from the source code? If so, how can I do it?

**Comment by pedrocamargo** [comment]
@RafalKucharskiPK , PyQt5 has been removed as a dependency, which should solve the problem you are having.

As discussed here https://github.com/AequilibraE/aequilibrae/issues/582, AequilibraE is not currently built for M1, as we are having problems on CI.  That issue is being tracked there, so I am closing this one.
