### ISSUE TITLE
Invalid dtype for AequilibraeMatrix index for memory_only matrix

### ISSUE THREAD

**Issue by elfjes** [AequilibraE/aequilibrae#424]
First of all, I like the new(ish) support for memory only matrices, and the performance benefits it offers. Edit: is it relatively new, or did just the default change recently?

However, I did run into an issue. When creating the indices for the AequilibraeMatrix, the numpy array has a `float` dtype, which means it can't actually be used for indexing: 
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

So I created a fix, PR coming up.

**Comment by pedrocamargo** [comment]
I came across that issue as well, but I was just overriding the indices when I could not that to work instead of digging to find the issue. Thanks for finding it, @elfjes .  Are you guys enjoying the much better performance already?

**Comment by elfjes** [comment]
Yeah, that's my workaround for now as well :)

haven't run any benchmarks yet, but definitely gonna give it a go
