### ISSUE TITLE
Complemento está obsoleto?

### ISSUE THREAD

**Issue by Githubcristiano** [AequilibraE/aequilibrae#430]
Boa Tarde!
Desinstalei pois não estava respondendo e ao instalar veio a mensagem que está obsoleto.
O projeto foi descontinuado? Ou há outra forma de instalação disponível?

![aequlibrae](https://github.com/AequilibraE/aequilibrae/assets/138624370/c063e8b9-c332-4fe5-b47f-296a3c3f1c46)

**Comment by pedrocamargo** [comment]
Leia as instruções do complementoe, quando for reportar um issue, siga as instruções para tal. 

http://www.aequilibrae.com/qgis/latest/getting_started/getting_started.html#getting-started ---- On Wed, 05 Jul 2023 06:39:39 +1000  ***@***.***  wrote ----
Boa Tarde!
Desinstalei pois não estava respondendo e ao instalar veio a mensagem que está obsoleto.
O projeto foi descontinuado? Ou há outra forma de instalação disponível?
