### ISSUE TITLE
OMX export to CSV is missing

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/aequilibrae#450]
It seems from https://github.com/AequilibraE/qaequilibrae/issues/227 that aequilibrae need some changes to allow the comeback of skim export function in an easily readable format (it's ok to display them but use them is better... :P)

Do somebody knows what needs to be changed exactly ?
If too complicated or long to do, does direct skims export to csv is still possible ? (to set qAequilibraE to do it directly)

**Comment by pedrocamargo** [comment]
The feature is available in aequilibrae, so it is just a qaequilibrae issue. So I have re-opened that issue on QAequilibraE and will close this one.
