### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by pedrocamargo** [AequilibraE/aequilibrae#452]
A new version of Python has been released. Supported is needed

**Comment by Jake-Moss** [comment]
I've just moved my dev environment over to 3.12.0, we'll see if I catch anything

**Comment by djfrancesco** [comment]
When I tried this new version, I had some troubles with some packages that were not supporting it yet. Maybe it was a little bit too soon...

**Comment by pedrocamargo** [comment]
It is DEFINITELY too soon. I'll trigger the pipeline every now and then and merge it when it passes.

**Comment by pedrocamargo** [comment]
AequilibraE 1.0 added this support

https://pypi.org/project/aequilibrae/#files
