### ISSUE TITLE
Excessive memory usage on gtfs import with existing project

### ISSUE THREAD

**Issue by Jake-Moss** [AequilibraE/aequilibrae#458]
**Describe the bug**
Excessive memory usage on gtfs import with existing project (>32gb). On a new project, the gtfs data can be imported with ~3gb. Found issue on the PuT assignment branch but it exist on develop as well.

**To Reproduce**
```python
from aequilibrae.project import Project
from aequilibrae.transit import Transit
project = Project()
project.open("aequilibrae_model")

data = Transit(project)
transit = data.new_gtfs_builder(agency="LISANCO", file_path="Lyon_GTFS_2022.zip")

dates = transit.dates_available()
transit.load_date(dates[0])
```

**Files**
Files on `PT assignment development` team,
```
Lyon_GTFS_2022.zip
lyon_aequilibrae_model.7z
```

**Comment by pedrocamargo** [comment]
This has been solved.
