### ISSUE TITLE
Failed to install in a arm64 based ubuntu docker

### ISSUE THREAD

**Issue by lindsaymorgan** [AequilibraE/aequilibrae#468]
I am trying to install this package in a arm64 based ubuntu docker and it keep fail when installing PyQt5 dependency, even if I install PyQt5 in previous and use --no-deps flag.
I also tried to build aquilibrae from source code by `python3 setup.py build_ext --inplace && pip3 install . ` , but it also try to install PyQt5 by itself.
**To Reproduce**
```
FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install build-essential autoconf automake libtool -y
RUN apt-get install libproj-dev libgeos-dev libjson-c-dev libpng-dev libjpeg-dev -y
RUN apt-get install -y git cmake python3 python3-dev python3-pip
RUN apt-get install -y wget
RUN apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev -y
RUN apt-get install libxcb1-dev libxcb-xinerama0-dev  -y
RUN apt-get install perl -y
RUN apt-get install libgl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev libxext-dev -y
RUN apt-get install -y libsqlite3-mod-spatialite
RUN apt-get install -y libspatialite-dev pandoc
RUN wget -O /etc/apt/sources.list https://repo.huaweicloud.com/repository/conf/Ubuntu-Ports-bionic.list
RUN apt-get update --allow-insecure-repositories
RUN apt-get upgrade -y --allow-unauthenticated
RUN apt-get install qtbase5-dev qt5-default -y
RUN cd /home/sip-4.19.13 && python3 configure.py --sip-module PyQt5.sip && make && make install
RUN cd /home/PyQt5_gpl-5.11.3 && python3 configure.py && make && make install
RUN pip3 install -i https://pypi.mirrors.ustc.edu.cn/simple aequilibrae --no-deps
```

**Screenshots**
![image](https://github.com/AequilibraE/aequilibrae/assets/25105493/37da414a-ba6d-4633-93c8-024a3cf9bfb6)

**Desktop (please complete the following information):**
 - OS: Ubuntu (arm64 base)
 - Python version 3.8.10
 - PyQt5 PyQt5_gpl-5.11.3

**Comment by pedrocamargo** [comment]
Can you provide a little more detail about the hardware you are using?

**Comment by pedrocamargo** [comment]
Fix was merged into develop and will be included in the next release

https://github.com/AequilibraE/aequilibrae/pull/522
