### ISSUE TITLE
Migrate CI to cibuildwheel

### ISSUE THREAD

**Issue by Jake-Moss** [AequilibraE/aequilibrae#488]
As https://github.com/RalfG/python-wheels-manylinux-build has been depreciated as of 6 months ago we should migrate the CI to the new https://github.com/pypa/cibuildwheel as new Python release are no longer present on the old CI.

**Comment by pedrocamargo** [comment]
I think this is done with the merging of the Route Choice branch. Isn't it, @Jake-Moss ?

**Comment by Jake-Moss** [comment]
Yep this is now complete
