### ISSUE TITLE
Discrepancy between select link calculated flows and assigned flows for CFW/BFW

### ISSUE THREAD

**Issue by mitsudz** [AequilibraE/aequilibrae#493]
**Purpose of use**
Problem found during SMP internship working on the ODME algorithm.

**Describe the bug**
When running an assignment with either conjugate franke-wolfe or biconjugate frank-wolfe, the select link analysis and assignment flow to not match up. In particular - following select link analysis we obtain a matrix which contains in each cell the amount of demand through the link originating from the corresponding origin-destination pair. Summing these up in theory should give the flow assigned by the algorithm for a given link-direction - however this differs from the results obtained from 
the assignment. This does not occur for algorithms other than cfw & bfw, and the discrepancy only occurs when we set the maximum number of iterations to > 1.

**To Reproduce**
Got to the odme branch at https://github.com/mitsudz/aequilibrae/tree/mitsudz/odme. Navigate to tests/aequilibrae/paths and see the script titled S_L_Problem_Script.ipynb. From here you can see code to create an example assignment object and run it with cfw (the same behaviour happens with bfw) with max iterations of 5 and check 2 selected links. The results there are shown in the screenshots below, and you can see the assigned and calculated flows differ in both cases.

**Screenshots**
<img width="517" alt="Screenshot 2024-01-16 at 4 21 11 pm" src="https://github.com/AequilibraE/aequilibrae/assets/86662260/cb3e3045-363d-4fb5-815c-696c18c24d43">
<img width="666" alt="Screenshot 2024-01-16 at 4 21 21 pm" src="https://github.com/AequilibraE/aequilibrae/assets/86662260/0b419eec-888d-4ad6-9886-bea8bd00cd25">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - Python version 3.10.12
 - Version - AequilibraE 0.9.4 (develop) - release name: Queluz

**Comment by pedrocamargo** [comment]
Wasn't this fixed, @Jake-Moss ?

**Comment by Jake-Moss** [comment]
Whoops, yes this was
