### ISSUE TITLE
Create Node Layer not working

### ISSUE THREAD

**Issue by jsender321** [AequilibraE/aequilibrae#50]
I have a line shapefile representing my roadway network loaded into QGIS 3.6.  I have selected that layer as my network layer in AequilibraE under the Network Preparation dialog.  I then clicked the "Create node layer" option, entered a node layer name and node numbering start, then clicked "Run!".  The dialog then sticks at 0% saying "Duplicating line layer".

![capture](https://user-images.githubusercontent.com/33093418/53592926-8c617680-3b54-11e9-9011-6f6b95219ffa.JPG)

**Comment by pedrocamargo** [comment]
Hey @jsender321 ,  can you make the dataset available so I can try to reproduce it?

**Comment by jsender321** [comment]
@pedrocamargo  Thanks for the quick reply!  I'm a little new to this, so hopefully the zipped shapefile attaches to this post.

[EC_Roads_1901.zip](https://github.com/AequilibraE/aequilibrae/files/2916787/EC_Roads_1901.zip)

**Comment by pedrocamargo** [comment]
And BTW... This bug actually belongs here: https://github.com/AequilibraE/AequilibraE-GUI/issues

There are two repositories for AequilibraE. One for the GUI and and for the Python package...

**Comment by pedrocamargo** [comment]
It turns out the layer you are working contains MultiLineStrings, which are not supported (It doesn't really make sense to have disjoint links in a transportation network). If you convert Multi-Parts to Single Parts you should be able to get going. 
You can also send questions to aequilibrae@googlegroups.com

**Comment by pedrocamargo** [comment]
The issue has already been raised, btw.  I will get there at some point  ;-)
https://github.com/AequilibraE/AequilibraE-GUI/issues/112

**Comment by jsender321** [comment]
Sorry I put this in the wrong spot.  Thanks so much for your help @pedrocamargo !
