### ISSUE TITLE
connect_mode - generated connectors are not connecting to the nearest node [v1.0.1]

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/aequilibrae#550]
When using the connect_mode function (with no link_types parameter, search polygon is a buffer around the centroid of 0.05 degree) : resulting connectors are not the shortest ones 😢

**Comment by Art-Ev** [comment]
![image](https://github.com/AequilibraE/aequilibrae/assets/83211842/6e0c1405-f6d7-4b34-8077-2ac3ffa8530e)

**Comment by pedrocamargo** [comment]
Is there a minimum example you could provide to help us reproduce this one?
