### ISSUE TITLE
Discussion forum?

### ISSUE THREAD

**Issue by Robinlovelace** [AequilibraE/aequilibrae#558]
With apologies for opening an issues unrelated to the code, was wondering where's best to open discussion topics. Context: will be trying to reproduce the code in the route choice example for Leeds. See https://github.com/ITSLeeds/routingday/issues/4 for details.

**Comment by Robinlovelace** [comment]
And was wanting to share with the Aequilibrae community, in the interests of sharing + open source.

**Comment by pedrocamargo** [comment]
Hey Robin. Thanks for sharing that. The best place to post is on the AequilibraE's mailing list:

https://groups.google.com/g/aequilibrae

**Comment by Robinlovelace** [comment]
Awesome, thanks! Will post there..
