### ISSUE TITLE
Can't select the Zode or Node Layer in Desire Lines Tool

### ISSUE THREAD

**Issue by paola-yumi** [AequilibraE/aequilibrae#65]
Hi, I need to create desire lines on my states layer, and I can't select anything on the 'Zode or Node Layer' nor on the 'ID Field' option.
![git-hub](https://user-images.githubusercontent.com/54673815/68332996-7da16b00-00b6-11ea-9f6f-efd60b78a460.png)
I'm new to QGIS so I don't know if I forgot something.
Thank you, in advance.

**Comment by pedrocamargo** [comment]
Paula,

Have you checked if your area layer is a Polygon layer?  MultiPolygon are
not supported.  I'd also need the layer itself (in case it is polygon) to
check what is going on.

**Comment by paola-yumi** [comment]
I think it is a MultiPolygon layer... Was it possible on previous versions? We're actually updating some tutorials on our class, and since the files and proceedings are the same than the previous tutorials, it should work with the same steps... 
![git-hub2](https://user-images.githubusercontent.com/54673815/68334247-facddf80-00b8-11ea-81a9-cf246bc715c6.png)

**Comment by pedrocamargo** [comment]
But can you make your tutorials publicly available?

**Comment by pedrocamargo** [comment]
MultiPolygons and MultiPoints created issues that made it necessary to
remove them, so I'm afraid they are not coming back.

**Comment by paola-yumi** [comment]
I understand... 
I think I can, but they are in Portuguese!

**Comment by pedrocamargo** [comment]
I'll translate them!

**Comment by pedrocamargo** [comment]
I am closing this issue, but let's transfer the discussion to aequilibrae@googlegroups.com

I am keen on having as many tutorials as possible and as many languages as possible!

**Comment by paola-yumi** [comment]
Thank you for the attention! I've sent the files via e-mail!
