### ISSUE TITLE
Matrix not importing when layer name is more than 50 characters

### ISSUE THREAD

**Issue by venuricj** [AequilibraE/aequilibrae#96]
When using QGIS version 3.4.9 on windows 10, the matrix file does not import when the file name of the csv is more than 54 characters in length.

**Comment by venuricj** [comment]
When using QGIS version 3.4.9 on windows 10, the matrix does not import when the layer name of the imported csv is more than 50 characters in length.

**Comment by pedrocamargo** [comment]
This bug report is for the QGIS GUI, and not the Python package, so I will close it here.
The issue tracker for that software is https://github.com/AequilibraE/AequilibraE-GUI/issues
